title:                     "Snooey Template"
url:                       "https://snooey-template.netlify.com"
baseurl:                   "/"
title_seperator:           " | " 
locale:                    "en"
timezone:                  "Australia/Brisbane"

social:
    facebook:       /
    twitter:        /
    linkedin:       /
    instagram:      /
    pinterest:      /
    youtube:        /
    github:         /
    stackoverflow:  /

plugins_dir:                _plugins
plugins: 
    - jekyll-archives 
    - jekyll-sitemap
    - jekyll-seo-tag

exclude:
    - LICENSE
    - README.md
    - .gitignore
    - Gemfile
    - Gemfile.lock
    
include:
    - _pages

collections:
    code:
        output: true
        permalink: /:collection/:path/
    documents:
        output: true
        permalink: /:collection/:path/
    projects:
        output: true
        permalink: /:collection/:path/
    snippets:
        output: true
        permalink: /:collection/:path/
    tldr:
        output: true
        permalink: /:collection/:path/
    videos:
        output: true
        permalink: /:collection/:path/
    wizards:
        output: true
        permalink: /:collection/:path/

collections_dir: collections

defaults:
    -   scope:
            path: ""
        values:
            title:              Lorem ipsum
            subtitle:           dolor sit amet.
            description:        Lorem ipsum dolor sit amet. Et unde quaerat aut earum animi aut explicabo saepe qui quibusdam accusamus ut velit asperiores vel natus temporibus. Qui sapiente saepe qui totam saepe est suscipit quia vel error provident cum omnis eius aut galisum rem nulla dolor? Qui internos voluptas est nulla odit est temporibus expedita eos quidem cumque. Ea voluptates eligendi quo rerum libero et molestiae harum vel fugit magni et cupiditate optio At quia consequuntur ut exercitationem laboriosam. Cum blanditiis voluptatibus At amet sunt At quia deleniti id quibusdam neque ut odio placeat.
            excerpt:            Lorem ipsum dolor sit amet.
            author:             Shane Hoey
            icon:               fas fa-rocket
            navigation:         default
            carousel:           #data file
            jumbotron:          #data file
            breadcrumb:         true #true false
            alert:              #data file
            heading:            false #true false
            images:             #data file   #CHECK WHAT THIS IS FOR ?
            footer:             default
            image:
                horizontal:     /assets/images/default/horizontal.jpg
                vertical:       /assets/images/default/vertical.jpg
                square:         /assets/images/default/square.jpg
                random:         https://source.unsplash.com/random/750x400
                background:     /assets/images/default/background.jpg
                profile:        /assets/images/profile/shanehoey.jpg
                mvp:            /assets/images/profile/MVPLogo-300x475.png
            order:              1000
    -   scope:
            path:               ""
            type:               "pages"
        values:
            layout:             "page"
            permalink:          /:basename/
    -   scope:
            path:               ""
            type:               "posts"
        values:
            layout:             "post"
    -   scope:
            path:               ""
            type:               "code"
        values:
            layout:             "code"
    -   scope:
            path:               ""
            type:               "documents"
        values:
            layout:             "documents"
            icon:               "far fa-file-code"
    -   scope:
            path:               ""
            type:               "projects"
        values:
            layout:             "projects"
            icon:               "far fa-file-code"
    -   scope:
            path:               ""
            type:               "snippets"
        values:
            layout:             "snippets"
    -   scope:
            path:               ""
            type:               "tldr"
        values:
            layout:             "tldr"
    -   scope:
            path:               ""
            type:               "videos"
        values:
            layout:             "videos"
    -   scope:
            path:               ""
            type:               "wizards"
        values:
            layout:             "wizards"